### ISSUE TITLE
npm audit proxy with Apache - example

### ISSUE THREAD

**Issue by VassilMarjunits** [chovyy/npm-audit-proxy#2]
Here is tested example with Apache to proxy npm audit.
https://stackoverflow.com/questions/68757527/configure-local-proxy-for-the-npm-audit-with-apache

**Comment by chovyy** [comment]
Dear @VassilMarjunits, thanks for this issue and your (?) post on SO. I had this mentioned 403 error too when I tried to proxy with Apache only. Do I understand it right, that when I set `ProxyPreserveHost off`, this piece of software becomes obsolete?

**Comment by xaviou** [comment]
Hi @chovyy, I used @VassilMarjunits Apache configuration detailed on SO and it worked, without having to install "this piece of software" ;-)

**Comment by chovyy** [comment]
Well yes, I don't use it myself anymore since @VassilMarjunits pointed me to the correct Apache settings.
